project:
  type: website
  output-dir: docs

website:
  repo-url: "https://github.com/tjmahr/quarto-blog"
  title: "Higher Order Functions"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: sandstone
    css: styles.css
    fig-width: 6
    fig-asp: 0.618
    fig-dpi: 300
    fig-align: "center"
    fig-cap-location: "margin"
    linkcolor: "#f5333b"
    fontsize: 1em
    linestretch: 1.5


